name: Python test runer 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

jobs:
  runTest:
    name: Corre los test del proyecto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepara Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Preparar dependencias para test
        run: |
          python -m pip install --upgrade pip
          pip install cryptography
      - name: Correr test de comandos de consola
        run: |
          python Test/TestConsola.py
          python Test/SubTetConsolaEncryptoManiac.py
      - name: Correr test de consola
        run: | 
          python Test/TestConsola.py
      - name: Correr test de Encrypto Maniac
        run: |
          python Test/TestEncryptoManiac.py
        
