# This is a basic workflow to help you get started with Actions

name: Python test runer 

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  runTest:
    name: corre los test del proyecto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Preparar dependencias para test
        run: |
          python -m pip install --upgrade pip
          pip install cryptography
      - name: Corriendo test de comandos de consola
        run: python testConsola.py
      - name: Correindo test de consola
        run: python testConsola.py
