name: Python test runer 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  runTest:
    name: Corre los test del proyecto
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepara Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Preparar dependencias para test
        run: |
          python3 -m pip3 install --upgrade pip3
          pip3 install -r requirements.txt
      - name: Correr todos los test.
        run: |
          python3 -m unittest discover -s ./Test/ -p *Test.py
